/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.cs.cs2210;
	
	
/**
 * 
 * 
 * <B><DT>名　　称：</B></DT>
 * 新报事单子表VO<BR />
 * <B><DT>说　　明：</B></DT>
 * <BR />
 * <B><DT>完整路径：</B></DT>
 * nc.vo.cs.cs2210
 * @author ouyb
 * @version UFIDA NC5.6
 * <B><DT>创建日期：</B></DT>
 * <DD>2015-10-15</DD>
 */
public class NewReportBVO  {
	private String vreportcontent;
	private String pk_newreport_b;
	private Integer ireportstatus;
	private Integer dr;
	private String pk_newreport;
    private String pk_content;
    private Integer bodyrow;
    private String vsourcebillid;
	public String getVreportcontent() {
		return vreportcontent;
	}
	public void setVreportcontent(String vreportcontent) {
		this.vreportcontent = vreportcontent;
	}
	public String getPk_newreport_b() {
		return pk_newreport_b;
	}
	public void setPk_newreport_b(String pk_newreport_b) {
		this.pk_newreport_b = pk_newreport_b;
	}
	public Integer getIreportstatus() {
		return ireportstatus;
	}
	public void setIreportstatus(Integer ireportstatus) {
		this.ireportstatus = ireportstatus;
	}
	public Integer getDr() {
		return dr;
	}
	public void setDr(Integer dr) {
		this.dr = dr;
	}
	public String getPk_newreport() {
		return pk_newreport;
	}
	public void setPk_newreport(String pk_newreport) {
		this.pk_newreport = pk_newreport;
	}
	public String getPk_content() {
		return pk_content;
	}
	public void setPk_content(String pk_content) {
		this.pk_content = pk_content;
	}
	public Integer getBodyrow() {
		return bodyrow;
	}
	public void setBodyrow(Integer bodyrow) {
		this.bodyrow = bodyrow;
	}
	public String getVsourcebillid() {
		return vsourcebillid;
	}
	public void setVsourcebillid(String vsourcebillid) {
		this.vsourcebillid = vsourcebillid;
	}
  
} 
